apiVersion: v1
kind: Pod
metadata:
  name: workflow-launcher-ms
  labels:
    app: workflow-launcher-ms
spec:
  nodeName: minikube
  containers:
  - name: microservice-workflow-launcher
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/oracle-code-brussels-microservices-choreography"
    - name: APP_HOME
      value: "WorkflowLauncher"
    - name: APP_STARTUP
      value: "WorkflowLauncher.js"
    - name: KAFKA_HOST
      value: "ubuntu"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "workflowEvents"
    - name: REDIS_HOST
      value: "redis-cache"
    - name: REDIS_PORT
      value: "6379"
    ports:
    lifecycle:
      postStart:
        exec:
          # add advertised host (ubuntu) of VM running Kafka to hosts file - with that VMs network interface's IP address
          command: ["sh","-c","echo 192.168.188.101 ubuntu > /etc/hosts"]
