apiVersion: v1
kind: Pod
metadata:
  name: workflow-launcher-ms
  labels:
    app: workflow-launcher-ms
spec:
  nodeName: minikube
  containers:
  - name: microservice-workflow-launcher
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/event-bus-microservices-backbone-jfall2017"
    - name: APP_HOME
      value: "WorkflowLauncher"
    - name: APP_STARTUP
      value: "WorkflowLauncher.js"
    - name: KAFKA_HOST
      value: "192.168.188.102"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "workflowEvents"
    - name: REDIS_HOST
      value: "redis-cache"
    - name: REDIS_PORT
      value: "6379"
    ports:
