apiVersion: v1
kind: Pod
metadata:
  name: tweet-enricher-ms
  labels:
    app: tweet-enricher-ms
spec:
  nodeName: minikube
  containers:
  - name: tweet-enricher
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/event-bus-microservices-backbone-jfall2017"
    - name: APP_PORT
      value: "8103"
    - name: APP_HOME
      value: "TweetEnricher"
    - name: APP_STARTUP
      value: "TweetEnricher.js"
    - name: KAFKA_HOST
      value: "192.168.188.102"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "workflowEvents"
    - name: REDIS_HOST
      value: "redis-cache"
    - name: REDIS_PORT
      value: "6379"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8103
    