apiVersion: v1
kind: Service
metadata:
  labels:
    name: tweettranslatorservice
  name: tweetentranslatorservice
spec:
  ports:
    # The port that this service should serve on.
    - port: 8118
      # port listened at inside the container
      targetPort: 8118
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: tweet-translator-ms
  type: NodePort