apiVersion: v1
kind: Pod
metadata:
  name: tweetreceiver-ms
  labels:
    app: tweetreceiver-ms
spec:
  nodeName: minikube
  containers:
  - name: tweetreceiver
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/microservices-choreography-kubernetes-workshop-june2017"
    - name: APP_PORT
      value: "8101"
    - name: APP_HOME
      value: "part4/TweetReceiver"
    - name: APP_STARTUP
      value: "TweetReceiver.js"
    - name: KAFKA_HOST
      value: "ubuntu"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "workflowEvents"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8101
    lifecycle:
      postStart:
        exec:
          # add advertised host (ubuntu) of VM running Kafka to hosts file - with that VMs network interface's IP address
          command: ["sh","-c","echo 192.168.188.101 ubuntu > /etc/hosts"]
