apiVersion: v1
kind: Pod
metadata:
  name: log-monitor-ms
  labels:
    app: log-monitor-ms
spec:
  nodeName: minikube
  containers:
  - name: log-monitor
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/oracle-code-brussels-microservices-choreography"
    - name: APP_PORT
      value: "8115"
    - name: APP_HOME
      value: "LogMonitor"
    - name: APP_STARTUP
      value: "LogMonitor.js"
    - name: KAFKA_HOST
      value: "ubuntu"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "logTopic"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8115
    lifecycle:
      postStart:
        exec:
          # add advertised host (ubuntu) of VM running Kafka to hosts file - with that VMs network interface's IP address
          command: ["sh","-c","echo 192.168.188.101 ubuntu > /etc/hosts"]
